import { defineGuide, type Helpers } from '../../lib/guide-types';

/** Salaire net mensuel en milieu ordinaire, sans autre ressource ni enfant. */
const x = (h: Helpers, s: number) => h.M.aah({ salaire: s });
const tranche = (h: Helpers) => h.P.aah.abattement_activite.tranche_smic_brut * h.P.smic.mensuel_brut;
const ines = 1000;

export default defineGuide({
  id: 'aah-cumul-salaire',
  group: 'handicap',
  order: 30,
  mini: 'aahCumulSalaire',
  related: ['simulateur-aah', 'aah-plafond-ressources', 'aah-enfants', 'aah-deconjugalisation', 'aah-pension-invalidite', 'simulateur-prime-activite'],
  sources: ['spAah', 'decretAah2026', 'spSmic'],
  fr: {
    slug: 'aah-et-salaire',
    nav: 'AAH et salaire',
    card: 'Les abattements de 80 % et 40 % sur le salaire, et le niveau de salaire où l’AAH s’arrête.',
    title: 'AAH et salaire 2026 : abattements de 80 % et 40 %, cumul',
    description: 'AAH et salaire en 2026 : 80 % du salaire ignoré jusqu’à 560 €, 40 % au-delà. L’AAH s’éteint vers 2 109 € net pour une personne seule. Tableau et simulateur.',
    h1: 'Travailler avec l’AAH : ce que le salaire retire vraiment',
    intro: 'Un salaire ne fait baisser l’AAH que d’une fraction de son montant : la règle des deux abattements permet de travailler sans tout perdre.',
    resume: (h) => `Un salaire tiré d’un emploi en milieu ordinaire ne réduit l’AAH que partiellement : ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} de la part du salaire inférieure à ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} du Smic brut, soit ${h.eur(tranche(h), 2)} par mois en 2026, sont ignorés, puis ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)} du reste. Avec ${h.eur(ines)} net par mois, la CAF ne retient que ${h.eur(x(h, ines).salaireRetenu, 2)} de ressources, et l’AAH estimée reste de ${h.eur(x(h, ines).aah, 2)}. Le revenu total atteint alors ${h.eur(ines + x(h, ines).aah, 2)}, contre ${h.eur(h.P.aah.montant_max, 2)} sans emploi. Pour une personne seule sans enfant ni autre ressource, l’AAH s’éteint vers ${h.eur(h.M.seuilSortieAah(0))} de salaire net mensuel. L’AAH reste en outre cumulable avec la prime d’activité, selon service-public. Ces chiffres sont des estimations au barème du 1er avril 2026 ; la CAF calcule le droit sur vos ressources déclarées.`,
    faqs: (h) => [
      { q: 'Je touche l’AAH et je trouve un mi-temps à 1 000 €, combien vais-je garder ?', a: `Environ ${h.eur(x(h, ines).aah, 2)} d’AAH par mois, en plus de votre salaire. Sur ${h.eur(ines)} net, ${h.eur(x(h, ines).abattement, 2)} sont ignorés grâce aux abattements, et seuls ${h.eur(x(h, ines).salaireRetenu, 2)} réduisent l’allocation. Votre revenu total passe à ${h.eur(ines + x(h, ines).aah, 2)}. Estimation pour une personne seule sans enfant, au montant maximal de ${h.eur(h.P.aah.montant_max, 2)}.` },
      { q: 'À partir de quel salaire perd-on complètement l’AAH ?', a: `Pour une personne seule sans enfant ni autre ressource, vers ${h.eur(h.M.seuilSortieAah(0))} net par mois selon notre moteur. Avec un enfant à charge, le plafond relevé de ${h.eur(h.P.aah.majoration_enfant)} par an porte ce seuil vers ${h.eur(h.M.seuilSortieAah(1))}. Une pension ou une rente, qui compte en entier, l’abaisse au contraire. Au-delà, le droit à l’AAH peut subsister mais le montant versé est nul.` },
      { q: 'Pourquoi les 560 premiers euros de salaire comptent-ils si peu pour l’AAH ?', a: `Parce que l’abattement est de ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} sur cette tranche, qui correspond à ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} du Smic brut mensuel de ${h.eur(h.P.smic.mensuel_brut, 2)}. Sur ${h.eur(tranche(h), 2)} gagnés, seuls ${h.eur(h.M.salaireRetenuAah(tranche(h)), 2)} sont retenus. Un petit temps partiel coûte donc très peu d’AAH : environ ${h.eur(h.P.aah.montant_max - x(h, tranche(h)).aah, 2)} par mois.` },
      { q: 'Un travail en Ésat est-il traité comme un salaire ordinaire pour l’AAH ?', a: `Non. Service-public indique que les règles de calcul diffèrent selon que vous travaillez en milieu ordinaire ou en établissement et service d’accompagnement par le travail (Ésat). Les abattements de ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} et ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)} décrits ici et notre simulateur ne concernent que l’emploi en milieu ordinaire. Pour un travailleur d’Ésat, rapprochez-vous de la CAF.` },
      { q: 'L’AAH se cumule-t-elle avec la prime d’activité quand on travaille ?', a: `Oui. La fiche AAH de service-public cite la prime d’activité parmi les prestations cumulables avec l’AAH. Les deux se demandent séparément auprès de la CAF. Notre estimation de ${h.eur(x(h, ines).aah, 2)} d’AAH pour un salaire de ${h.eur(ines)} ne comprend pas la prime d’activité, qui se calcule avec le simulateur dédié, sur les revenus du foyer.` },
    ],
    body: (h) => `
<h2>Deux abattements, une tranche</h2>
<p>La règle tient en deux taux. Sur la partie du salaire mensuel qui ne dépasse pas ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} du Smic brut, soit ${h.eur(tranche(h), 2)} avec le Smic de ${h.eur(h.P.smic.mensuel_brut, 2)} publié par la ${h.src('spSmic', 'fiche Smic de service-public')}, ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} sont ignorés. Au-delà, l’abattement passe à ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)}. Ce qui reste, le salaire retenu, se retire du montant maximal de ${h.eur(h.P.aah.montant_max, 2)} fixé par le ${h.src('decretAah2026', 'décret du 30 mars 2026')}.</p>
<p>La ${h.src('spAah', 'fiche AAH de service-public')} confirme le principe : les traitements et salaires font partie des revenus pris en compte partiellement. Les revenus fonciers, eux, comptent en entier.</p>
${h.table(['Salaire net mensuel', 'Salaire retenu', 'AAH estimée', 'Salaire + AAH'], [300, Math.round(tranche(h)), 800, ines, 1300, h.P.smic.mensuel_net, 1800].map((s) => [h.eur(s), h.eur(x(h, s).salaireRetenu, 2), h.eur(x(h, s).aah, 2), h.eur(s + x(h, s).aah, 2)]), 'Personne seule, sans enfant ni autre ressource, barème du 1er avril 2026 (estimation)', ['r', 'r', 'r', 'r'])}
<!--mini:aahCumulSalaire-->

<h2>Inès passe de zéro à mi-temps</h2>
<p>Inès, 38 ans, a une AAH à taux plein de ${h.eur(h.P.aah.montant_max, 2)}. Elle reprend un poste de secrétaire à mi-temps dans une PME, payé ${h.eur(ines)} net. Sur les ${h.eur(tranche(h), 2)} premiers euros, seuls ${h.eur(h.M.salaireRetenuAah(tranche(h)), 2)} comptent. Sur les ${h.eur(ines - tranche(h), 2)} suivants, ${h.pct(1 - h.P.aah.abattement_activite.taux_haut, 0)} sont retenus. Au total, la CAF compte ${h.eur(x(h, ines).salaireRetenu, 2)} de ressources par mois et l’AAH d’Inès devient ${h.eur(x(h, ines).aah, 2)}.</p>
<p>Son revenu passe de ${h.eur(h.P.aah.montant_max, 2)} à ${h.eur(ines + x(h, ines).aah, 2)}, soit ${h.eur(ines + x(h, ines).aah - h.P.aah.montant_max, 2)} de plus chaque mois, avant même la prime d’activité qu’elle peut demander en parallèle. Sur 100 € de salaire au-delà de la tranche, Inès en garde environ ${h.eur(100 * (1 - (1 - h.P.aah.abattement_activite.taux_haut)), 0)} ; sous la tranche, environ ${h.eur(100 * h.P.aah.abattement_activite.taux_bas, 0)}.</p>

<h2>Salaire et rente : le mélange qui coûte cher</h2>
<p>Les abattements ne valent que pour le salaire. Une personne qui cumule un emploi à 800 € net et une rente d’accident du travail de 300 € voit les deux traitées différemment : le salaire n’est retenu que pour ${h.eur(h.M.salaireRetenuAah(800), 2)}, la rente l’est en entier. Son AAH estimée tombe à ${h.eur(h.M.aah({ salaire: 800, autres: 300 }).aah, 2)}, contre ${h.eur(x(h, 800).aah, 2)} avec le seul salaire. Les 300 € de rente lui coûtent donc 300 € d’AAH, alors que 300 € de salaire supplémentaire, au-delà de la tranche, ne lui en coûteraient que ${h.eur(300 * (1 - h.P.aah.abattement_activite.taux_haut), 0)}.</p>
<p>Cette différence explique des écarts d’AAH entre deux personnes au revenu total identique. Elle compte aussi au moment de choisir entre un temps partiel thérapeutique, une reprise à temps plein ou le maintien d’une pension : à revenu égal, la part qui vient d’un salaire laisse plus d’AAH que celle qui vient d’une pension ou d’une rente. La page ${h.a('aah-pension-invalidite', 'AAH et pension d’invalidité')} détaille le cas des pensions.</p>
<h2>Plus de salaire, toujours plus de revenu</h2>
<p>Le revenu total ne recule jamais quand le salaire monte. Entre le Smic net et 1 800 €, la personne de notre tableau gagne ${h.eur(1800 + x(h, 1800).aah - h.P.smic.mensuel_net - x(h, h.P.smic.mensuel_net).aah, 2)} de plus pour ${h.eur(1800 - h.P.smic.mensuel_net, 2)} de salaire supplémentaire. Le gain reste partiel tant que l’AAH est versée, puis il devient entier au-delà du seuil de sortie.</p>

<h2>Le seuil de sortie, et ce qui le déplace</h2>
<p>Pour une personne seule sans enfant ni autre ressource, l’AAH tombe à zéro vers ${h.eur(h.M.seuilSortieAah(0))} de salaire net mensuel, nettement au-dessus du Smic net de ${h.eur(h.P.smic.mensuel_net, 2)}. Trois éléments déplacent ce seuil. Les enfants à charge le relèvent fortement : ${h.eur(h.M.seuilSortieAah(1))} avec un enfant, ${h.eur(h.M.seuilSortieAah(2))} avec deux, comme le montre la page ${h.a('aah-enfants', 'AAH et enfants')}. Une pension, une rente ou des loyers perçus l’abaissent, puisqu’ils comptent sans abattement. Enfin, en couple, l’ancien calcul conjugalisé peut s’appliquer s’il est plus favorable, ce que détaille la page ${h.a('aah-deconjugalisation', 'déconjugalisation de l’AAH')}.</p>

<h2>Ce qu’il faut savoir avant de reprendre un emploi</h2>
<p>La demande d’AAH déclenche systématiquement une procédure de reconnaissance de la qualité de travailleur handicapé, la RQTH, selon service-public. Il n’y a donc pas de démarche séparée à engager pour l’obtenir au moment de la demande. Côté allocation, c’est le montant qui s’ajuste aux ressources, selon les abattements décrits plus haut.</p>
<p>Notre estimation raisonne sur un salaire mensuel stable. Les ressources prises en compte par la CAF et leur période de référence peuvent différer d’un cas à l’autre, notamment entre une demande initiale et un renouvellement ; les écarts avec un premier versement s’expliquent souvent ainsi. Pour votre situation, le ${h.a('simulateur-aah', 'simulateur AAH')} accepte salaire, pension et enfants, et le ${h.a('simulateur-prime-activite', 'simulateur de prime d’activité')} complète le tableau.</p>
`,
  },
  en: {
    slug: 'aah-and-wages',
    nav: 'AAH and wages',
    card: 'The 80% and 40% allowances on earnings, and the pay level at which AAH stops.',
    title: 'AAH and Wages 2026: The 80% and 40% Earnings Allowance',
    description: 'AAH and wages in 2026: 80% of pay ignored up to €560, 40% above that. AAH stops at around €2,109 net for a single person. Table, worked example and calculator.',
    h1: 'Working on AAH: what your wage really takes off',
    intro: 'A wage only lowers AAH by a fraction of its amount: two allowances on earnings let you work without losing everything.',
    resume: (h) => `Pay from a mainstream job only partly reduces the AAH (allocation aux adultes handicapés, France’s allowance for disabled adults): ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} of the part of pay below ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} of the gross minimum wage, ${h.eur(tranche(h), 2)} a month in 2026, is ignored, then ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)} of the rest. On ${h.eur(ines)} net a month, the CAF (family benefits office) counts only ${h.eur(x(h, ines).salaireRetenu, 2)} of resources, and estimated AAH stays at ${h.eur(x(h, ines).aah, 2)}. Total income then reaches ${h.eur(ines + x(h, ines).aah, 2)}, against ${h.eur(h.P.aah.montant_max, 2)} without a job. For a single person with no children or other income, AAH runs out at around ${h.eur(h.M.seuilSortieAah(0))} of net monthly pay. AAH can also be combined with the prime d’activité (in-work bonus), according to service-public.fr. These are estimates at the 1 April 2026 rates; the CAF works out the entitlement from your declared resources.`,
    faqs: (h) => [
      { q: 'I am on AAH and found a €1,000 half-time job, how much will I keep?', a: `About ${h.eur(x(h, ines).aah, 2)} of AAH a month on top of your pay. Of the ${h.eur(ines)} net, ${h.eur(x(h, ines).abattement, 2)} is ignored thanks to the allowances, and only ${h.eur(x(h, ines).salaireRetenu, 2)} reduces the benefit. Your total income rises to ${h.eur(ines + x(h, ines).aah, 2)}. Estimate for a single person with no children, from the ${h.eur(h.P.aah.montant_max, 2)} maximum.` },
      { q: 'At what wage does AAH stop completely?', a: `For a single person with no children or other income, at around ${h.eur(h.M.seuilSortieAah(0))} net a month according to our engine. With one dependent child, the ceiling rises by ${h.eur(h.P.aah.majoration_enfant)} a year and the threshold moves to about ${h.eur(h.M.seuilSortieAah(1))}. A pension or annuity, counted in full, lowers it instead. Beyond it, the right may remain but the amount paid is zero.` },
      { q: 'Why do the first €560 of pay count so little towards AAH?', a: `Because the allowance on that band is ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)}, and the band equals ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} of the ${h.eur(h.P.smic.mensuel_brut, 2)} gross monthly minimum wage. Of ${h.eur(tranche(h), 2)} earned, only ${h.eur(h.M.salaireRetenuAah(tranche(h)), 2)} is counted. A small part-time job therefore costs very little AAH: about ${h.eur(h.P.aah.montant_max - x(h, tranche(h)).aah, 2)} a month.` },
      { q: 'Is work in an Ésat treated like ordinary pay for AAH?', a: `No. Service-public.fr says the calculation rules differ between mainstream employment and an Ésat (établissement et service d’accompagnement par le travail, a sheltered work setting). The ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} and ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)} allowances described here, and our calculator, only cover mainstream jobs. If you work in an Ésat, ask the CAF.` },
      { q: 'Can AAH be combined with the activity bonus when I work?', a: `Yes. The service-public.fr AAH sheet lists the prime d’activité among benefits that can be combined with AAH. You claim them separately from the CAF. Our estimate of ${h.eur(x(h, ines).aah, 2)} of AAH on a ${h.eur(ines)} wage does not include the activity bonus, which you can work out with the dedicated calculator, based on household income.` },
    ],
    body: (h) => `
<h2>Two allowances, one band</h2>
<p>The rule comes down to two rates. On the part of monthly pay up to ${h.pct(h.P.aah.abattement_activite.tranche_smic_brut, 0)} of the gross Smic (minimum wage), ${h.eur(tranche(h), 2)} with the ${h.eur(h.P.smic.mensuel_brut, 2)} Smic published on the ${h.src('spSmic', 'service-public.fr Smic sheet')}, ${h.pct(h.P.aah.abattement_activite.taux_bas, 0)} is ignored. Above that, the allowance drops to ${h.pct(h.P.aah.abattement_activite.taux_haut, 0)}. What is left, the counted wage, comes off the ${h.eur(h.P.aah.montant_max, 2)} maximum set by the ${h.src('decretAah2026', 'decree of 30 March 2026')}.</p>
<p>The ${h.src('spAah', 'service-public.fr AAH sheet')} confirms the principle: wages and salaries are among the incomes counted only in part. Rental income, by contrast, counts in full.</p>
${h.table(['Net monthly pay', 'Pay counted', 'Estimated AAH', 'Pay + AAH'], [300, Math.round(tranche(h)), 800, ines, 1300, h.P.smic.mensuel_net, 1800].map((s) => [h.eur(s), h.eur(x(h, s).salaireRetenu, 2), h.eur(x(h, s).aah, 2), h.eur(s + x(h, s).aah, 2)]), 'Single person, no children or other income, rates from 1 April 2026 (estimate)', ['r', 'r', 'r', 'r'])}
<!--mini:aahCumulSalaire-->

<h2>Inès goes from nothing to half-time</h2>
<p>Inès, 38, receives the full ${h.eur(h.P.aah.montant_max, 2)} of AAH. She takes a half-time admin job at a small firm, paying ${h.eur(ines)} net. Of the first ${h.eur(tranche(h), 2)}, only ${h.eur(h.M.salaireRetenuAah(tranche(h)), 2)} counts. Of the next ${h.eur(ines - tranche(h), 2)}, ${h.pct(1 - h.P.aah.abattement_activite.taux_haut, 0)} is counted. In all, the CAF counts ${h.eur(x(h, ines).salaireRetenu, 2)} of resources a month and Inès’s AAH becomes ${h.eur(x(h, ines).aah, 2)}.</p>
<p>Her income rises from ${h.eur(h.P.aah.montant_max, 2)} to ${h.eur(ines + x(h, ines).aah, 2)}, ${h.eur(ines + x(h, ines).aah - h.P.aah.montant_max, 2)} more each month, before any activity bonus she may claim alongside. For each €100 of pay above the band, Inès keeps about ${h.eur(100 * (1 - (1 - h.P.aah.abattement_activite.taux_haut)), 0)}; below the band, about ${h.eur(100 * h.P.aah.abattement_activite.taux_bas, 0)}.</p>

<h2>Wages plus an annuity: the costly mix</h2>
<p>The allowances only apply to wages. Someone combining an €800 net job with a €300 work-injury annuity sees the two treated differently: the wage is counted at only ${h.eur(h.M.salaireRetenuAah(800), 2)}, the annuity in full. Estimated AAH falls to ${h.eur(h.M.aah({ salaire: 800, autres: 300 }).aah, 2)}, against ${h.eur(x(h, 800).aah, 2)} with the wage alone. The €300 annuity therefore costs €300 of AAH, whereas €300 more pay above the band would cost only ${h.eur(300 * (1 - h.P.aah.abattement_activite.taux_haut), 0)}.</p>
<p>That difference explains AAH gaps between two people with the same total income. It also matters when weighing part-time work on medical grounds against a return to full time, or against keeping a pension: for the same income, the share that comes from wages leaves more AAH than the share that comes from a pension or annuity. The page on ${h.a('aah-pension-invalidite', 'AAH and a disability pension')} covers pensions in detail.</p>
<h2>More pay always means more income</h2>
<p>Total income never falls as pay rises. Between the net minimum wage and €1,800, the person in our table gains ${h.eur(1800 + x(h, 1800).aah - h.P.smic.mensuel_net - x(h, h.P.smic.mensuel_net).aah, 2)} for ${h.eur(1800 - h.P.smic.mensuel_net, 2)} of extra pay. The gain is partial while AAH is still paid, and becomes complete beyond the exit threshold. If you come from a country where disability benefits stop abruptly once you earn a set amount, this gradual taper is the main difference to keep in mind.</p>

<h2>The exit threshold, and what moves it</h2>
<p>For a single person with no children or other income, AAH reaches zero at around ${h.eur(h.M.seuilSortieAah(0))} of net monthly pay, well above the ${h.eur(h.P.smic.mensuel_net, 2)} net minimum wage. Three things move that threshold. Dependent children raise it sharply: ${h.eur(h.M.seuilSortieAah(1))} with one child, ${h.eur(h.M.seuilSortieAah(2))} with two, as the page on ${h.a('aah-enfants', 'AAH with children')} shows. A pension, an annuity or rent received lowers it, since they count with no allowance. And in a couple, the old joint calculation may apply where it is more favourable, as explained on the page on ${h.a('aah-deconjugalisation', 'AAH and a partner’s income')}.</p>

<h2>Before you go back to work</h2>
<p>An AAH claim always triggers a RQTH procedure (reconnaissance de la qualité de travailleur handicapé, official recognition as a disabled worker), according to service-public.fr. So there is no separate step to take to obtain it when you claim. On the allowance side, it is the amount that adjusts to your resources, through the allowances described above.</p>
<p>Our estimate assumes a steady monthly wage. The resources the CAF counts, and the reference period it uses, can vary from case to case, for instance between a first claim and a renewal, which often explains a gap with the first payment. For your own situation, the ${h.a('simulateur-aah', 'AAH calculator')} takes wage, pension and children, and the ${h.a('simulateur-prime-activite', 'activity bonus calculator')} completes the picture.</p>
`,
  },
});
