import { defineGuide, type Helpers } from '../../lib/guide-types';

const af = (h: Helpers, enfants: number, revenus: number, majorables = 0, vingtAns = 0) => h.M.allocationsFamiliales({ enfants, majorables, revenus, vingtAns });
const pl = (h: Helpers) => h.M.plafondsAf(3);
const gain = (h: Helpers, t: 0 | 1 | 2) => h.M.baseAf(3, t) - h.M.baseAf(2, t);

export default defineGuide({
  id: 'allocations-familiales-3-enfants',
  group: 'famille',
  order: 30,
  mini: 'afTroisEnfants',
  miniHref: 'simulateur-allocations-familiales',
  related: ['simulateur-allocations-familiales', 'allocations-familiales-2-enfants', 'allocations-familiales-4-enfants', 'complement-familial', 'allocation-forfaitaire-20-ans'],
  sources: ['spAf', 'instructionPf2026', 'spCf'],
  fr: {
    slug: 'allocations-familiales-3-enfants',
    nav: 'Allocations familiales, 3 enfants',
    card: 'Pourquoi le troisième enfant fait plus que doubler l’allocation, et les droits qu’il ouvre en plus.',
    title: 'Allocations familiales 3 enfants 2026 : 347,32 € et plus',
    description: 'Allocations familiales 2026 pour 3 enfants : 347,32 € par mois sous 86 644 € de revenus 2024, plus 76,13 € par adolescent éligible. Gain du 3e enfant chiffré.',
    h1: 'Allocations familiales avec trois enfants',
    intro: 'À trois enfants, le barème change d’échelle : le montant fait plus que doubler, chaque adolescent compte et d’autres prestations s’ouvrent.',
    resume: (h) => `Une famille de trois enfants touche ${h.eur(h.M.baseAf(3, 0), 2)} d’allocations familiales par mois en 2026 tant que son revenu net catégoriel ${h.P.af.revenus_reference} reste sous ${h.eur(pl(h)[0])}, contre ${h.eur(h.M.baseAf(2, 0), 2)} avec deux enfants : le troisième rapporte à lui seul ${h.eur(gain(h, 0), 2)} par mois. Entre ${h.eur(pl(h)[0])} et ${h.eur(pl(h)[1])}, le montant est de ${h.eur(h.M.baseAf(3, 1), 2)} ; au-delà, de ${h.eur(h.M.baseAf(3, 2), 2)}. À la différence d’une famille de deux, chaque enfant né avant le ${h.date(h.P.af.bascule_majoration)} ajoute sa majoration, l’aîné compris : ${h.eur(h.P.af.majoration[0], 2)} par enfant au premier niveau. Trois enfants ouvrent aussi deux autres droits : le complément familial, une fois que le plus jeune a ${h.P.cf.age_min} ans, et l’allocation forfaitaire versée un an quand l’aîné atteint ${h.P.af.age_limite} ans. Les revenus retenus sont ceux de l’avis d’imposition 2025. Les montants, nets de CRDS, sont des estimations : la CAF seule calcule le droit.`,
    faqs: (h) => [
      { q: 'Combien rapporte un troisième enfant en allocations familiales ?', a: `Au premier niveau de revenus, ${h.eur(gain(h, 0), 2)} de plus par mois : la famille passe de ${h.eur(h.M.baseAf(2, 0), 2)} à ${h.eur(h.M.baseAf(3, 0), 2)}, soit ${h.eur(gain(h, 0) * 12)} sur un an. Le plafond monte aussi, de ${h.eur(h.M.plafondsAf(2)[0])} à ${h.eur(pl(h)[0])}. À revenus élevés, le gain reste de ${h.eur(gain(h, 2), 2)} par mois, d’après le barème publié par service-public.` },
      { q: 'Avec trois enfants, l’aîné a-t-il droit à la majoration pour âge ?', a: `Oui. L’exclusion de l’aîné ne vaut que pour les familles de deux enfants. À trois, chaque enfant né avant le 1er mars 2012 ouvre une majoration de ${h.eur(h.P.af.majoration[0], 2)} au premier niveau de revenus. Une famille à 60 000 € dont les deux aînés remplissent la condition reçoit ${h.eur(af(h, 3, 60000, 2).total, 2)} par mois au lieu de ${h.eur(af(h, 3, 60000).total, 2)}.` },
      { q: 'Nos trois enfants ont 1, 4 et 7 ans : avons-nous droit au complément familial ?', a: `Pas encore. Le complément familial exige au moins trois enfants à charge tous âgés de ${h.P.cf.age_min} ans et plus, selon service-public. D’après la fiche, il est versé à partir du troisième anniversaire du plus jeune, si le revenu ${h.P.cf.revenus_reference} ne dépasse pas ${h.eur(h.P.cf.plafonds.un_revenu[0])} pour un couple à un revenu. En attendant, seules les allocations familiales sont versées.` },
      { q: 'Nous déclarons 95 000 € avec trois enfants, combien verse la CAF ?', a: `Avec 95 000 € de revenu net catégoriel ${h.P.af.revenus_reference}, le foyer dépasse ${h.eur(pl(h)[0])} mais reste sous ${h.eur(pl(h)[1])} : l’allocation est divisée par deux, ${h.eur(af(h, 3, 95000).total, 2)} par mois. Chaque enfant né avant mars 2012 y ajoute ${h.eur(h.P.af.majoration[1], 2)}. Ce calcul suit le barème 2026 publié par service-public.` },
      { q: 'Le troisième enfant est-il compté s’il vit chez son autre parent ?', a: `Seulement s’il est à votre charge effective et permanente, selon la définition de service-public : vous assurez son entretien et son éducation. Un enfant qui vit en permanence chez son autre parent, qui l’entretient, relève du foyer de celui-ci. Si vos deux autres enfants restent seuls à votre charge, vous relevez du barème de deux enfants, ${h.eur(h.M.baseAf(2, 0), 2)} au premier niveau au lieu de ${h.eur(h.M.baseAf(3, 0), 2)}. La garde alternée obéit à des règles propres, que notre simulateur ne traite pas.` },
      { q: 'Que touche une famille de trois enfants quand l’aîné atteint 20 ans ?', a: `L’aîné cesse d’être compté : la famille passe au barème de deux enfants, ${h.eur(h.M.baseAf(2, 0), 2)} au premier niveau. Pendant un an, une allocation forfaitaire de ${h.eur(h.P.af.forfait_20_ans[0], 2)} amortit la baisse s’il vit encore au foyer et gagne peu, d’après service-public. Sans elle, la chute serait de ${h.eur(h.M.baseAf(3, 0) - h.M.baseAf(2, 0), 2)} par mois.` },
    ],
    body: (h) => `
<h2>Le troisième enfant fait plus que doubler l’allocation</h2>
<p>Le barème des allocations familiales n’est pas proportionnel. Le deuxième enfant ouvre un petit montant ; le troisième en ajoute un bien plus gros. Au premier niveau de revenus, il pèse ${h.eur(gain(h, 0), 2)} par mois, davantage que les deux premiers réunis. Cette pente vient de la façon dont les textes fixent les montants : un pourcentage de la base mensuelle de calcul des allocations familiales (BMAF) de ${h.pct(h.P.af.taux_bmaf.deux, 0)} pour deux enfants, de ${h.pct(h.P.af.taux_bmaf.trois, 0)} pour trois, selon l’${h.src('instructionPf2026', 'instruction du 20 mars 2026')}.</p>
${h.table(['Niveau de revenus', '2 enfants', '3 enfants', 'Apport du 3e'], ([0, 1, 2] as const).map((t) => [['Montant plein', 'Divisé par 2', 'Divisé par 4'][t], h.eur(h.M.baseAf(2, t), 2), h.eur(h.M.baseAf(3, t), 2), h.eur(gain(h, t), 2)]), 'Montants mensuels nets de CRDS depuis le 1er avril 2026, hors majorations', ['l', 'r', 'r', 'r'])}
<!--mini:afTroisEnfants-->

<h2>L’arrivée du troisième, mois par mois</h2>
<p>La famille Roussel a deux enfants de 4 et 7 ans et déclare 52 000 € de revenu net catégoriel ${h.P.af.revenus_reference}. Elle reçoit ${h.eur(af(h, 2, 52000).total, 2)} par mois. Le troisième naît le 20 mars. Le droit au barème de trois enfants s’ouvre le mois suivant, en avril, et le premier versement majoré arrive début mai, puisque la CAF paie à terme échu. Désormais : ${h.eur(af(h, 3, 52000).total, 2)} par mois, soit ${h.eur((af(h, 3, 52000).total - af(h, 2, 52000).total) * 12)} de plus sur une année pleine.</p>
<p>Trois ans plus tard, au troisième anniversaire du benjamin, la question du complément familial se pose. Si un seul des parents travaille, le plafond est de ${h.eur(h.P.cf.plafonds.un_revenu[0])} : avec 52 000 €, rien. Si les deux ont chacun gagné au moins ${h.eur(h.P.paje.seuil_deuxieme_revenu)} dans l’année de référence, le plafond passe à ${h.eur(h.P.cf.plafonds.deux_revenus[0])} et le foyer reçoit ${h.eur(h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: true, revenus: 52000 }).cf, 2)} de plus par mois. Pour un même revenu total, la répartition entre les deux parents décide donc du droit.</p>

<h2>Les plafonds d’une famille de trois</h2>
<p>Pour trois enfants, le montant plein est versé jusqu’à ${h.eur(pl(h)[0])} de revenu net catégoriel ${h.P.af.revenus_reference}, la moitié jusqu’à ${h.eur(pl(h)[1])}, le quart au-delà, d’après la ${h.src('spAf', 'fiche service-public')}. Ces plafonds dépassent de ${h.eur(pl(h)[0] - h.M.plafondsAf(2)[0])} ceux d’une famille de deux. Un couple qui déclare 84 000 € reste ainsi au montant plein, ${h.eur(af(h, 3, 84000).total, 2)} par mois, alors qu’avec deux enfants il serait déjà au niveau réduit.</p>
<p>Juste au-dessus d’un plafond, un ${h.a('complement-degressif', 'complément dégressif')} lisse la baisse : c’est d’ailleurs sur une famille de trois enfants à 87 000 € que service-public construit son exemple officiel.</p>

<h2>Trois adolescents, combien de majorations ?</h2>
<p>La famille Martin a trois enfants : Lucas, né en 2010, Emma, née en janvier 2012, et Noah, né en mai 2012 d’une autre union du père. Lucas et Emma sont nés avant le ${h.date(h.P.af.bascule_majoration)} : chacun ouvre la majoration à ${h.P.af.age_majoration_ancien} ans. Noah, lui, est né après cette date ; sa majoration n’arrivera qu’à ${h.P.af.age_majoration_nouveau} ans. Avec 60 000 € de revenus, la CAF verse ${h.eur(af(h, 3, 60000, 2).total, 2)} par mois aujourd’hui.</p>
<p>Si la famille n’avait eu que Lucas et Emma, une seule majoration aurait été due, celle d’Emma. Le troisième enfant change donc aussi la règle des majorations, pas seulement le montant de base. Le calendrier précis figure sur la page ${h.a('majoration-allocations-familiales', 'majoration pour âge')}.</p>

<h2>Le complément familial, à partir des 3 ans du plus jeune</h2>
<p>Trois enfants à charge âgés de ${h.P.cf.age_min} à moins de ${h.P.cf.age_max} ans ouvrent le ${h.a('complement-familial', 'complément familial')}, sous plafond de revenus, selon la ${h.src('spCf', 'fiche service-public du complément familial')}. Un couple à un seul revenu qui déclare 40 000 € reçoit ${h.eur(h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: false, revenus: 40000 }).cf, 2)} de plus par mois. Ajouté aux ${h.eur(af(h, 3, 40000).total, 2)} d’allocations familiales, le foyer perçoit ${h.eur(af(h, 3, 40000).total + h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: false, revenus: 40000 }).cf, 2)} par mois. Tant que le benjamin n’a pas ${h.P.cf.age_min} ans, ce complément n’est pas dû.</p>

<h2>Quand l’aîné sort du compte</h2>
<p>À ${h.P.af.age_limite} ans, l’aîné ne compte plus et la famille redescend au barème de deux enfants. Le choc est amorti par l’${h.a('allocation-forfaitaire-20-ans', 'allocation forfaitaire des 20 ans')}, versée pendant un an. Le même événement fait souvent tomber le complément familial, qui exige trois enfants de moins de ${h.P.cf.age_max} ans : il disparaît l’année suivante, quand l’aîné atteint cet âge. Ce sont deux baisses successives à prévoir, et une famille qui s’agrandit avec un ${h.a('allocations-familiales-4-enfants', 'quatrième enfant')} les décale d’autant.</p>
<p>Le ${h.a('simulateur-allocations-familiales', 'simulateur')} chiffre chacune de ces étapes.</p>
`,
  },
  en: {
    slug: 'family-allowance-three-children',
    nav: 'Family allowance, 3 children',
    card: 'Why the third child more than doubles the allowance, and the extra entitlements it opens.',
    title: 'Family Allowance 3 Children 2026: €347.32 a Month and Up',
    description: 'Family allowance 2026 for 3 children in France: €347.32 a month below €86,644 of 2024 income, plus €76.13 per eligible teenager. What a third child adds.',
    h1: 'Family allowance with three children',
    intro: 'At three children the scale shifts: the amount more than doubles, every teenager counts and other benefits open up.',
    resume: (h) => `A family with three children receives ${h.eur(h.M.baseAf(3, 0), 2)} of family allowance (allocations familiales) a month in 2026 while its ${h.P.af.revenus_reference} net income stays below ${h.eur(pl(h)[0])}, compared with ${h.eur(h.M.baseAf(2, 0), 2)} for two children: the third child alone is worth ${h.eur(gain(h, 0), 2)} a month. Between ${h.eur(pl(h)[0])} and ${h.eur(pl(h)[1])}, the amount is ${h.eur(h.M.baseAf(3, 1), 2)}; above that, ${h.eur(h.M.baseAf(3, 2), 2)}. Unlike a two-child family, each child born before ${h.date(h.P.af.bascule_majoration)} adds a supplement, the eldest included: ${h.eur(h.P.af.majoration[0], 2)} per child at the lowest income level. Three children also open two more rights: the family supplement (complément familial) once the youngest is ${h.P.cf.age_min}, and a flat-rate payment for one year when the eldest turns ${h.P.af.age_limite}. Income is the revenu net catégoriel on the 2025 tax assessment notice. Amounts are net of the CRDS levy and are estimates: only the CAF, the family benefits office, decides.`,
    faqs: (h) => [
      { q: 'How much extra family allowance does a third child bring?', a: `At the lowest income level, ${h.eur(gain(h, 0), 2)} more a month: the family goes from ${h.eur(h.M.baseAf(2, 0), 2)} to ${h.eur(h.M.baseAf(3, 0), 2)}, or ${h.eur(gain(h, 0) * 12)} over a year. The ceiling rises too, from ${h.eur(h.M.plafondsAf(2)[0])} to ${h.eur(pl(h)[0])}. On high incomes the gain is still ${h.eur(gain(h, 2), 2)} a month, according to the scale on service-public.fr.` },
      { q: 'With three children, does the eldest get the age supplement?', a: `Yes. Excluding the eldest only applies to two-child families. With three, every child born before 1 March 2012 opens a supplement of ${h.eur(h.P.af.majoration[0], 2)} at the lowest income level. A family on €60,000 whose two eldest qualify receives ${h.eur(af(h, 3, 60000, 2).total, 2)} a month instead of ${h.eur(af(h, 3, 60000).total, 2)}.` },
      { q: 'Our three children are 1, 4 and 7: can we claim the family supplement?', a: `Not yet. The family supplement (complément familial) requires at least three dependent children all aged ${h.P.cf.age_min} or over, according to service-public.fr. Per that page, it is paid from the youngest's third birthday, if ${h.P.cf.revenus_reference} income is no higher than ${h.eur(h.P.cf.plafonds.un_revenu[0])} for a one-income couple. Until then, only family allowance is paid.` },
      { q: 'We declared €95,000 with three children, what does the CAF pay?', a: `With €95,000 of ${h.P.af.revenus_reference} net income, the household is above ${h.eur(pl(h)[0])} but below ${h.eur(pl(h)[1])}: the allowance is halved, ${h.eur(af(h, 3, 95000).total, 2)} a month. Each child born before March 2012 adds ${h.eur(h.P.af.majoration[1], 2)}. This follows the 2026 scale published on service-public.fr, net of the CRDS deduction.` },
      { q: 'Does a third child count if they live with their other parent?', a: `Only if you provide the child's effective and permanent care, in service-public.fr's definition: you pay for their upkeep and are responsible for their upbringing. A child living permanently with the other parent, who supports them, belongs to that parent's household. If only your other two children depend on you, you fall under the two-child scale, ${h.eur(h.M.baseAf(2, 0), 2)} at the lowest level instead of ${h.eur(h.M.baseAf(3, 0), 2)}. Shared custody follows its own rules, which our calculator does not handle.` },
      { q: 'What does a three-child family get when the eldest turns 20?', a: `The eldest is no longer counted, so the family moves to the two-child scale, ${h.eur(h.M.baseAf(2, 0), 2)} at the lowest level. For one year, a flat-rate payment of ${h.eur(h.P.af.forfait_20_ans[0], 2)} softens the drop if the young adult still lives at home and earns little, says service-public.fr. Without it the fall would be ${h.eur(h.M.baseAf(3, 0) - h.M.baseAf(2, 0), 2)} a month.` },
    ],
    body: (h) => `
<h2>The third child more than doubles the allowance</h2>
<p>French family allowance is not proportional. The second child opens a small amount; the third adds a much larger one. At the lowest income level it is worth ${h.eur(gain(h, 0), 2)} a month, more than the first two put together. That slope comes from how the amounts are set: a percentage of the monthly family benefit base (BMAF), ${h.pct(h.P.af.taux_bmaf.deux, 0)} for two children and ${h.pct(h.P.af.taux_bmaf.trois, 0)} for three, according to the ${h.src('instructionPf2026', 'instruction of 20 March 2026')}.</p>
${h.table(['Income level', '2 children', '3 children', 'Added by the 3rd'], ([0, 1, 2] as const).map((t) => [['Full rate', 'Halved', 'Quartered'][t], h.eur(h.M.baseAf(2, t), 2), h.eur(h.M.baseAf(3, t), 2), h.eur(gain(h, t), 2)]), 'Monthly amounts net of CRDS from 1 April 2026, before supplements', ['l', 'r', 'r', 'r'])}
<!--mini:afTroisEnfants-->

<h2>The third child's arrival, month by month</h2>
<p>The Roussel family has two children aged 4 and 7 and declares €52,000 of ${h.P.af.revenus_reference} net income. It receives ${h.eur(af(h, 2, 52000).total, 2)} a month. The third baby is born on 20 March. The three-child rate opens the following month, April, and the first higher payment lands in early May, because the CAF pays in arrears. From then on: ${h.eur(af(h, 3, 52000).total, 2)} a month, or ${h.eur((af(h, 3, 52000).total - af(h, 2, 52000).total) * 12)} more over a full year.</p>
<p>Three years later, on the youngest's third birthday, the family supplement comes into play. If only one parent works, the ceiling is ${h.eur(h.P.cf.plafonds.un_revenu[0])}: on €52,000, nothing. If each parent earned at least ${h.eur(h.P.paje.seuil_deuxieme_revenu)} in the reference year, the ceiling rises to ${h.eur(h.P.cf.plafonds.deux_revenus[0])} and the household gets ${h.eur(h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: true, revenus: 52000 }).cf, 2)} more a month. For the same total income, how it is split between the two parents decides the entitlement.</p>

<h2>Income ceilings for a family of three</h2>
<p>For three children, the full amount is paid up to ${h.eur(pl(h)[0])} of ${h.P.af.revenus_reference} revenu net catégoriel (net income by category, from your avis d'imposition), half up to ${h.eur(pl(h)[1])}, and a quarter above, per the ${h.src('spAf', 'service-public.fr page')}. These ceilings are ${h.eur(pl(h)[0] - h.M.plafondsAf(2)[0])} higher than for two children. A couple declaring €84,000 therefore stays on the full rate, ${h.eur(af(h, 3, 84000).total, 2)} a month, whereas with two children it would already be on the reduced level.</p>
<p>Just over a ceiling, a ${h.a('complement-degressif', 'tapering top-up')} smooths the drop; service-public.fr's own worked example is a three-child family on €87,000.</p>

<h2>Three teenagers, how many supplements?</h2>
<p>The Martin family has three children: Lucas, born in 2010, Emma, born in January 2012, and Noah, born in May 2012 from the father's earlier relationship. Lucas and Emma were born before ${h.date(h.P.af.bascule_majoration)}, so each opens the supplement at ${h.P.af.age_majoration_ancien}. Noah was born after that date; his supplement only comes at ${h.P.af.age_majoration_nouveau}. On €60,000 of income, the CAF pays ${h.eur(af(h, 3, 60000, 2).total, 2)} a month today.</p>
<p>Had the family only had Lucas and Emma, a single supplement would be due, Emma's. So the third child changes the supplement rule as well as the base amount. The exact timetable is on the ${h.a('majoration-allocations-familiales', 'age supplement')} page.</p>

<h2>The family supplement, from the youngest's third birthday</h2>
<p>Three dependent children aged ${h.P.cf.age_min} to under ${h.P.cf.age_max} open the ${h.a('complement-familial', 'family supplement')}, subject to an income ceiling, according to the ${h.src('spCf', 'service-public.fr family supplement page')}. A one-income couple declaring €40,000 receives ${h.eur(h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: false, revenus: 40000 }).cf, 2)} more a month. Added to ${h.eur(af(h, 3, 40000).total, 2)} of family allowance, the household gets ${h.eur(af(h, 3, 40000).total + h.M.complementFamilial({ enfants3a21: 3, deuxRevenus: false, revenus: 40000 }).cf, 2)} a month. Until the youngest is ${h.P.cf.age_min}, the supplement is not due.</p>

<h2>When the eldest drops out of the count</h2>
<p>At ${h.P.af.age_limite}, the eldest no longer counts and the family falls back to the two-child scale. The shock is cushioned by the ${h.a('allocation-forfaitaire-20-ans', 'age-20 flat-rate allowance')}, paid for a year. The same child often ends the family supplement too, since it needs three children under ${h.P.cf.age_max}: it goes the following year, when the eldest reaches that age. Plan for two successive cuts; a family that grows with a ${h.a('allocations-familiales-4-enfants', 'fourth child')} pushes them back.</p>
<p>The ${h.a('simulateur-allocations-familiales', 'calculator')} prices each of these steps.</p>
`,
  },
});
